### ISSUE TITLE
Feat : 일대일 채팅방

### ISSUE THREAD

**Issue by richsubin** [GoLAB-Project/GoLAB-frontend#10]
## Issue: Feature
친구들과 일대일 대화를 할 수 있는 일대일 채팅방

## Description
좌측에 친구목록이 뜨고 해당 친구를 클릭하면 우측에 친구와의 대화기록/ 채팅방이 보임

## Todo
- [x] 친구목록
- [x] 클릭시 해당 친구와의 대화창 가져옴
- [x] 말풍선을 텍스트 길이에 따라 어떻게 조정되어야하는지 생각해보자
- [x] 스크롤 자동으로 아래로 가게끔 하기
- [x] 채팅 헤더부분 만들기
- [x] 채팅 scroll 이쁘게 만들기
- [ ] backend friendList 불러오기

## ETC
- 사용자 아무도 클릭 안하면 그냥 고래  캐릭터 하나 띠용 있음
