### ISSUE TITLE
Feat : 토론방 목록 페이지 

### ISSUE THREAD

**Issue by richsubin** [GoLAB-Project/GoLAB-frontend#5]
## Issue: Feature
토론 게임 처음 들어갔을 때, 보이는 방 목록 페이지

## Description
목록에는 커스텀전, 일반전만 있다.
랭킹전은 방 목록에 노출이 되지 않고 자동 참여 된다.

## Todo
- [x] 방 이름 검색
- [x] 페이지네이션 : 한 페이지 8개 노출
- [x] 필터(공개방, 비공개방, 일반전, 커스텀전, 참여인원)
- [x] 모드 선택하는 모달창1
- [x] 모달창1에서 모드 선택하면 아래로 확장되도록 하기
- [x] 비공개방 클릭시 비밀번호 입력창

## ETC
필터 : 참여인원, 토론 시작한 방, 커스텀/일반, 공개방/비공개방
기존에는 방 만들기에 있는데 랭킹전 바로 참여할 수 있는 버튼을 만들면 어떨까..?

- FIX : 참여 버튼 누르면 해당 방 페이지로 이동
- FIX : 참여인원 부분에 현재 참여중인 인원 / 설정된 인원 표시되도
- 커스텀전 생성할 때 방 랜덤설정, 비밀번호 설정 등등 이것저것 디테일한게 많이 필요

**Comment by mukhoplus** [comment]
랭킹전은 MMR 기반 matching system으로 가는거 아니었나요??

**Comment by richsubin** [comment]
> 랭킹전은 MMR 기반 matching system으로 가는거 아니었나요??

맞아! 지금은 피그마 보면 토론방참여 > 랭킹전 버튼 있는데 랭킹전 버튼만 아예 목록 페이지로 따로 빼내올까 생각했던거였어

**Comment by mukhoplus** [comment]
아 음... 이런 느낌인가요??
![image](https://github.com/GoLAB-Project/GoLAB-frontend/assets/67003627/be2fdd29-3700-4802-a1f3-018ca1b57ceb)

**Comment by skybluelion** [comment]
오 아예 저렇게 채널 따로 파는거도 나쁘지는 않긴한데 랭킹전 참여자들끼리 전체 채팅은 있는게 좋을지 말지는 잘 모르겠음

**Comment by richsubin** [comment]
일단 이렇게 피그마대로 만들었고, 별로면 승완이가 보여준 예시처럼 수정해볼게
<img width="747" alt="image" src="https://github.com/GoLAB-Project/GoLAB-frontend/assets/81276634/16763a5d-6975-4362-b36d-0beec82a2505">

**Comment by mukhoplus** [comment]
FIX 2번 공감합니다
