### ISSUE TITLE
Feat : 토론 게임방

### ISSUE THREAD

**Issue by richsubin** [GoLAB-Project/GoLAB-frontend#6]
## Issue: Feature
토론 게임 방에 들어갔을 때 보이는 페이지 퍼블리싱 및 1차 완료

## Description
방 번호 및 방 이름이 담겨있는 헤더, 채팅 공간, role에 따라 우측 버튼 구성 달라짐. 참여자 리스트, 타이머

## Todo
- [x] 채팅 입력 및 채팅 올라오는 공간
- [ ] 타이머
- [x] role에 따라 달라지는 버튼
- [x] 방번호 및 이름, 나가기 버튼 있는 헤더
- [x] 참여자 리스트
- [ ] 주제, 키워드 선택

## ETC
버튼 구성
- default : 준비하기/준비완료
- player : 항복하기
- observer : 승자투표 버튼
